sudo: required

services:
  - docker

before_install:
- docker build -t fossday/gohugo .
- docker run -it -v $(pwd)/site:/src -v $(pwd)/public:/src/public fossday/gohugo

deploy:
  name: FOSS Team Deployment
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
