sudo: required

services:
  - docker

script:
  - docker build -t fossday/gohugo .
  - docker run --rm -v $(pwd)/site:/src -v $(pwd)/public:/src/public fossday/gohugo
  - echo $?

after_success:
- ls -la site
- ls -la site/public

deploy:
  name: FOSS Team Deployment
  provider: pages
  local_dir: site/public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  target_branch: master
  on:
    repo: raffaeldutra/fossday.github.io
    branches:
      only:
        - develop
