# Rafael Dutra
sudo: required

services:
  - docker

script:
  - docker build --no-cache -t fossday/gohugo .
  - docker run --rm -v $(pwd)/site:/src -v $(pwd)/site/public:/src/public fossday/gohugo
  - docker run --rm -v $(pwd)/site:/src -v $(pwd)/site/public:/src/public fossday/gohugo ls -la /src/public
  - docker --version

public:
  name: "FOSS Team Deployment"
  provider: pages
  local_dir: site/public
  skip_cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  target_branch: master
  on:
    branch: develop
