baseURL = "https://fossday.org"
languageCode = "pt-br"
title = "FOSSDay"
theme = "conference"

[permalinks]
  paginas = "/:filename"
  eventos = "/:filename"

[taxonomies]
  category = "categories"
  tag = "tags"
