baseurl: "https://fossday.org"
title: "Primeiro Foss Day Lajeado"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "FossDay Lajeado"
  Description: "Primeiro evento FOSS Day Lajeado. Participação do ilustre \"Maddog\""
  Date: "5 de Maio de 2018"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Univates"
  Address: "UNIVATES"
  City:  "Lajeado"
  State: "Rio Grande do Sul"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "AIzaSyD0SXo4PtQAlft4ERHwSlsGjQ6RYyF20hc"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    # - support
    - partners
    - presenter

  # Titles which you can translate to other languages
  Titles:
    about: "Sobre"
    location: "Local"
    speakers: "Palestrantes"
    schedule: "Grade"
    sponsors: "Patrocinadores"
    partners: "Parceiros"
    contact: "Contato"
    presenter: "Realização"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Faça seu registro!"
    link: "https://goo.gl/wtmEEE"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/fossday/site"

  # List of Sponsors
  Sponsors:
    - name: "Solis"
      logo: "/img/sponsors/solis.png"
      url: "http://www.solis.com.br"
    - name: "DA Engenharia de Software Univates"
      logo: "/img/partners/engenharia.png"
      url: ""
      
  # List of Partners
  Partners:
    - name: "Adriano Ott"
      logo: "/img/partners/adriano.png"
      url: "https://www.adrianoott.com.br/"
    - name: "LPI"
      logo: "/img/partners/lpi.png"
      url: "https://lpi.org"
    - name: "Novatec"
      logo: "/img/partners/novatec.png"
      url: "https://novate.com.br"
    - name: "Traço D"
      logo: "/img/partners/tracod.jpg"
      url: "http://www.tracod.com.br"


  # List of Support
  Presenter:
    - name: "Taquari Valley"
      logo: "/img/presenter/taquari_valley.png"
      url: "https://www.facebook.com/taquarivalley"


  # The entire schedule
  Schedule:
    - name: "Recepção + Coffee"
      time: "08:30"

    - name: "Abertura do evento + avisos"
      photo: "/img/speakers/fossday-logo.jpeg"
      bio: ""
      company: ""
      link:
        href: "http://fossday.org"
        text: ""
      presentation:
        title: "Abertura do evento"
        description: "-"
        time: "09h05"

    - name: "Jon \"Maddog\" Hall"
      photo: "/img/speakers/maddog.png"
      bio: "Jon \"Maddog\" Hall é o Diretor Executivo da Linux International, CEO da OptDyn e presidente do conselho do Linux Professional Institute. O apelido lhe foi dados por seus alunos na Hartford State Technical College, onde ele era Chefe do Departamento de Ciência da Computação. O próprio Hall afirma que o apelido “vem de um tempo em que eu tinha pouco controle sobre o meu temperamento”. Jon trabalha com informática desde 1969, trabalhou para a Western Electric Corporation, Aetna Life and Casualty, Bell Laboratories, Digital Equipment Corporation, VA Linux Systems, e SGI."
      company: "Diretor Executivo da Linux International, CEO da OptDyn e presidente do conselho do Linux Professional Institute."
      link:
        href: "http://twitter.com/maddoghall"
        text: "@maddoghall"
      presentation:
        title: "Computação em nuvem, Criptomoedas e Blockchain"
        description: "Independente do que você escolher para trabalhar, seguindo a atualidade e tendências tecnológicas -- inteligência artificial, robótica, internet das coisas, ciência de dados, criptomoedas, contratos inteligentes .. --, você estará trabalhando com softwares livres, de código aberto, a base de tudo isso. Jon \"maddog\" Hall, presidente do conselho do Linux Professional Institute irá falar de sua experiência no mercado de trabalho com software livre e estará à disposição para responder suas perguntas."
        time: "09h10"

    - name: "Cesar Brod"
      photo: "/img/speakers/cesar_brod.jpg"
      bio: "Diretor de Desenvolvimento de Comunidades do Linux Professional Institute para a América Latina e Caribe, que reside em Lajeado no Rio Grande do Sul.
      Atua na área de informática desde 1982. Sua formação profissional deu-se em grande parte nos Estados Unidos, Canadá e França. Começou a trabalhar com o Linux em 1993 e, desde 1997 desenvolve, através da BrodTec, serviços de consultoria, gestão de projetos e criação de modelos de negócios que têm por base softwares de código aberto."
      link:
        href: "http://www.brod.com.br"
        text: "http://www.brod.com.br"
      presentation:
        title: "Testes de aceitação para Web"
        description: "Um dos assuntos mais importantes e também o mais menosprezado por equipes de desenvolvimento são os testes. Reconhecidamente, a curva de aprendizagem para manter uma cobertura completa de testes em todo o software é extensa e aguda. É preciso infectar os desenvolvedores com o bicho testador para que eles reconheçam o valor dos testes tanto na proteção de seu código quanto na eliminação de débito técnico e dos bugs, verdadeiros ovos de alien que, se não tratados, tomarão conta de todo o planeta.
        Nesta apresentação, que é extraída do curso \"Introdução a Testes Ágeis\", Cesar irá mostrar como implementar testes de aceitação simples, usando o plugin Katalon Automation Recorder e a linguagem Python."
        time: "10h00"

    - name: "Convidados"
      photo: "/img/speakers/fossday-logo.jpeg"
      bio: ""
      company: ""
      link:
        href: ""
        text: ""
      presentation:
        title: "Painel: Tecnologia e Software Livre"
        description: "-"
        time: "11h00"

    - name: "Rafael Dutra"
      photo: "/img/speakers/rafael_dutra.jpg"
      bio: "Rafael Dutra é Administrador de Sistemas e entusiasta DevOps. Utiliza Linux desde 2005 e atualmente trabalha como Arquiteto SAAS para Jive Software pela Crossover"
      company: "Crossover/Jive Software"
      link:
        href: "http://rafaeldutra.me"
        text: "@raffaeldutra"
      presentation:
        title: "Docker Workshop (iniciante e intermediário)."
        description: "Um hands on para iniciarmos no mundo de containers utilizando Docker"
        time: "11h00"

    - name: "Almoço"
      time: "12h00"

    - name: "Rafael Dutra"
      photo: "/img/speakers/rafael_dutra.jpg"
      bio: "Rafael Dutra é Administrador de Sistemas e entusiasta DevOps. Utiliza Linux desde 2005 e atualmente trabalha como Arquiteto SAAS para Jive Software pela Crossover"
      company: "Crossover/Jive Software"
      link:
        href: "http://rafaeldutra.me"
        text: "@raffaeldutra"
      presentation:
        title: "Docker Workshop (iniciante e intermediário)"
        description: "Continuação do Workshop sobre Docker"
        time: "13h00"

    - name: "Fabio Beneditto"
      photo: "/img/speakers/fabio.jpg"
      bio: "Entusiasta de Software Livre desde 1999, Desenvolvedor Web desde 2008, Graduado em Sistemas para Internet em 2015, voluntário no SUMO (Suporte Mozilla) e no Tchelinux."
      company: "DBC Company"
      link:
        href: "https://about.me/fabiobeneditto"
        text: "https://about.me/fabiobeneditto"
      presentation:
        title: "...porque no MEU TEMPO"
        description: "Voltada para todos os tipos de público, é uma apresentação / comparação sobre as tecnologias atuais em relação às disponíveis há 10 ou 15 anos atrás. Distribuições de Software, configuração de hardware, programas, redes sociais: o quanto isso pode mudar em 15 anos?"
        time: "13h00"


    - name: "Regis Tomkiel"
      photo: "/img/speakers/regis.jpg"
      bio: "Graduando em Sistemas de informação, desenvolvedor web e cofundador da produtora e agência Dose Extra Multimídia. Entusiasta de Software Livre desde 2006, quando conheceu o Slackware. Atualmente desenvolve praticamente todos os trabalhos de produção de vídeo nativamente numa distro GNU/Linux e com softwares renomados no mercado."
      company: "Dose Extra Multimídia"
      link:
        href: "regis@doseextra.com"
        text: "@regis"
      presentation:
        title: "Conheça a Web estática"
        description: "Conheça o mundo dos geradores de sites estáticos e comece o seu próprio projeto em minutos.
Palestra introdutória sobre o gerador de sites escrito em GO, o Hugo. Serão apresentados exemplos, dicas e o fundamental para colocar o primeiro projeto no ar."
        time: "14h00"

    - name: "Coffee-break"
      time: "15h00"

    - name: "Pablo Dall'Oglio"
      photo: "/img/speakers/pablo.jpeg"
      bio: "Pablo Dall’Oglio é graduado em Análise de Sistemas e mestre em Engenharia de Software pela Universidade do Vale do Rio dos Sinos (Unisinos). Autor dos livros PHP-GTK – Criando aplicações gráficas com PHP e Criando relatórios com PHP, tem grande experiência no desenvolvimento de sistemas para gestão de negócios e está constantemente envolvido com projeto e implementação de softwares orientados a objetos.Atualmente dedica-se à sua empresa, a Adianti Solutions (adianti.com.br), onde constrói ferramentas de produtividade como o Adianti Framework (adianti.com.br/framework) e o Adianti Reports (adianti.com.br/reports), além de prestar consultoria em projeto e desenvolvimento de sistemas orientados a objetos."
      company: "Adianti Solutions"
      link:
        href: "https://www.adianti.com.br/"
        text: "https://www.adianti.com.br/"
      presentation:
        title: "Criando software para o futuro com DDD, Arquitetura, Patterns, e Atitude"
        description: "Nesta palestra abordaremos diferentes aspectos do desenvolvimento de software, relacionados à modelagem, arquitetura, cultura, e padrões, que influenciam a criação de softwares adaptáveis para mudanças futuras."
        time: "15h30"

    - name: "Rauber"
      photo: "/img/speakers/rauber.jpg"
      bio: "Professor e pesquisador em assuntos relacionados a tecnologias de software e hardware livres e ao ecossistema hacker/ maker e de startups. Professor no SENAC Santa Cruz do Sul e in company; Voluntário nos projetos educacionais CodeClubeBrasil.org e JabutiEdu.org e no Grupo Tchelinux.org; Doutorando em Gestão e Tecnologia Ambiental, Mestre em Nanociências, Especialista em Gerenciamento de Projetos, Bacharel em Ciência da Computação e Técnico em Informática; Palestras em Campus Party/ Latinoware/ FISL/ FGSL e em eventos locais; Mentorias em Startups Weekends;"
      company: ""
      link:
        href: "https://fb.com/luizrauber"
        text: "https://fb.com/luizrauber"
      presentation:
        title: "25 minutos de dicas pra se aprimorar em informática!"
        description: "Com título auto-explicativo, nesta \"fala\" eu vou passar umas dicas de coisas aprendidas nos quase 10 anos de eventos e contribuições ao mundo do software livre. Assim dentro do tempo espera-se que aprenda sobre eventos, perfil e currículo (nesta ordem mesmo)."
        time: "16h30"

    - name: "Encerramento"
      time: "17:00"
